
#- name: Install and configure db
#  apt: name={{item}} state=latest
#  become: yes
#  with_items:
#    - postgresql-server
#    - postgresql-contrib
#    - postgresql-devel
#    - python-psycopg2
#

- name: Include db variables
  include_vars: group_vars/db.yml

- name: Start and enable postgres
  service: name=postgresql enabled=yes state=started
  become: yes

- name: Create database
  postgresql_db: name={{ app_name }}
  become_user: postgres
  become: yes

- name: Configure a new postgresql user
  postgresql_user:
    db={{ app_name }}
    name={{ db_user }}
    password={{ db_password }}
    priv=ALL
    role_attr_flags=NOSUPERUSER
  become: yes
  become_user: postgres
  notify:
    - restart postgres